version: '3'

services:
  drupal:
    image: drupal:8-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html/modules
      - ./html:/var/www/html/profiles
      - ./html:/var/www/html/themes
      - ./html:/var/www/html/sites
    restart: always
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nr2020nr
      MYSQL_USER: nraigosam
      MYSQL_PASSWORD: nr2020nr
      MYSQL_DATABASE: proyecto1-tele-indi
